# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:lifeshield
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Logging
logging.level.com.example.lifeshieldai=DEBUG

# VirusTotal
virustotal.api.key=0053b3a72eb6a6bb1f80408bcc02235bd4d3745a744dfa3369e6641aa902be9e