# PostgreSQL (Render)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# H2 console off
spring.h2.console.enabled=false

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-postgresql.sql
spring.sql.init.data-locations=classpath:data-postgresql.sql

# Logging
logging.level.com.example.lifeshieldai=INFO

# VirusTotal
virustotal.api.key=${VIRUSTOTAL_API_KEY:}
